i3lock -i  "$(cat ~/.fehbg | tail -1 | cut -d "'" -f2)"\
    --clock \
    --time-color=ffffff \
    --date-color=ffffff \
    --time-size=48 \
    --date-size=30 \
    --time-font="Maple Nerd Font"\
    --date-font="Raleway"\
    --indicator \
    --ring-width=10\
    --radius=160 \ 
    --ring-color=b58900 \
    --inside-color=00000066 \
    --keyhl-color=ff5555
