i3lock -i  "$(cat ~/.fehbg | tail -1 | cut -d "'" -f2)" -F \
    --bar-indicator \
    --bar-base-width=2 \
    --bar-pos="h-2"\
    --clock \
    --time-color=fb8500\
    --date-color=e07a5f\
    --time-size=80 \
    --date-size=36 \
    --time-font="Raleway:bold"\
    --date-font="Raleway"\
    --time-pos="w/2:ty+320"\
    --date-pos="tx:ty+80"\
    --blur=8 \
    --greeter-font="Maple Mono NF CN"\
    --greeter-text="$(fortune)"\
    --greeter-size=24\
    --greeter-pos="w/2:h-80"\
    --greeter-color="219ebc"
